### ISSUE TITLE
[Bug]: Lag showing things in container

### ISSUE THREAD

**Issue by Rad233** [melontini/m-tweaks#12]
### What happened?

When opening chests and villager gui(perhaps there would be more) ,items in chests or villager trades are shown about 0.5s later. This happens in my modpack.

### Screenshots

https://i.postimg.cc/nrMY31hj/1.png

### Mod Version

0.4.14

### Minecraft Version

- [X] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3

**Comment by Rad233** [comment]
> Hi, thanks for the report!
> 
> Can you please share your modlist? I can't seem to reproduce this in a bare-bones setup.

I found that the conflicting mod is extshape: https://www.curseforge.com/minecraft/mc-mods/extended-block-shapes

**Comment by melontini** [comment]
This seems to be a performance issue with the `Auto-generate Recipe Advancements` option, as blacklisting `extshape` fixed the problem for me (it generates 3983 advancements 🤨). Since Extended Block Shapes already generates advancements for itself, you can add `extshape` to the blacklisted namespaces. Otherwise, I'm really not sure 😅.

![screenshot_mt_bug](https://user-images.githubusercontent.com/104443436/231215353-4204830b-b0fe-4270-b0cf-4a214abd1e2f.png)

As for smaller flickers, they also happen without m-tweaks.

**Comment by Rad233** [comment]
Fixed, thanks!

**Comment by melontini** [comment]
So, a little update on this. This is an issue with how InventoryChangedCriterion is triggered. It goes through every advancement every time you open your inventory (or any inventory update for that matter). 

In the next version, I'll add an option to enable splitting InventoryChangedCriterion trigger to the worker thread, so that Server Thread doesn't have to wait. (It's experimental, but should fix the issue).
