### ISSUE TITLE
[Bug] Campfire feature not compatible with Lithium mod

### ISSUE THREAD

**Issue by Rad233** [melontini/m-tweaks#8]
**Describe the bug**
When used with lithium, campfire won't heal nearby player.
But adding this`    mixin.world.block_entity_ticking=false` line in lithium config fixes that.
This should be reported to lithium devs but I guess they won't fix that since it's a feature.
**Environment:**
 - 1.18.2 fabric
 - tweaks 0.4.5
 - lithium 0.10.3

**Comment by melontini** [comment]
ohno

This happens because of this mixin [CampfireBlockEntityMixin](https://github.com/CaffeineMC/lithium-fabric/blob/1.18.2/backport/src/main/java/me/jellysquid/mods/lithium/mixin/world/block_entity_ticking/sleeping/campfire/CampfireBlockEntityMixin.java)

I'll try to make the block entity wake up if there are players nearby
Otherwise, I'll just disable it by default via [fabric.mod.json](https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json)

Thanks for the heads-up!

**Comment by melontini** [comment]
Should be fixed in the latest release!
